defaults:
  - trainer: paged_adamw-descent

name: "phi-1_5"
hf_key: "microsoft/phi-1_5"

args:
  use_flash_attention_2: false
  torch_dtype:
    _target_: hydra.utils.get_object
    path: torch.bfloat16

trainer:
  args:
    bf16: true
    bf16_full_eval: true
    # deepspeed: "config/ds_config.json"
