name: real_toxic_prompt_challenge
dataset_path: "datasets/real_toxic_prompts_challenge/sampled_${.sample_num}"
sample_num: 1000
hf_key: "allenai/real-toxicity-prompts"
hf_split: "train"
prompt_label: "prompt"
prompt_toxic_label: "challenging"
prompt_text_field: "text"
