name: non_toxic_civil_comments
hf_key: "google/civil_comments"
hf_subset: ""
hf_splits: ["train", "validation", "test"]
dataset_base_dir: "datasets/civil_comments_non_toxic"
sample_ratio: 0.02
split: "sampled_${.sample_ratio}"
sub_dir_name: ""
dataset_path: "${.dataset_base_dir}/${.split}"
toxic_label: "toxicity"
toxic_type: "non-toxic"
toxicity_threshold: 0.2
text_field: "text"
