name: toxigen_non_toxic
hf_key: "skg/toxigen-data"
hf_subset: "train"
hf_splits: ["train"]
dataset_base_dir: "datasets/toxigen_non_toxic"
split: "sampled_${.sample_ratio}"
sample_ratio: 0.32
sub_dir_name: ""
dataset_path: "${.dataset_base_dir}/${.split}"
toxic_label: "roberta_prediction"
toxic_type: "non-toxic"
toxicity_threshold: 0.2
text_field: "generation"
