name: civil_comments_toxic
hf_key: "google/civil_comments"
hf_subset: ""
hf_splits: ["train", "validation", "test"]
dataset_base_dir: "datasets/civil_comments_toxic"
split: "all"
sub_dir_name: ""
dataset_path: "${.dataset_base_dir}/${.split}"
toxic_label: "toxicity"
toxic_type: "toxic"
toxicity_threshold: 0.8
text_field: "text"
