name: toxigen_toxic
hf_key: "skg/toxigen-data"
hf_subset: "train"
hf_splits: ["train"]
dataset_base_dir: "datasets/toxigen_toxic"
split: "all"
sub_dir_name: ""
dataset_path: "${.dataset_base_dir}/${.split}"
toxic_label: "roberta_prediction"
toxic_type: "toxic"
toxicity_threshold: 0.8
text_field: "generation"
